namespace UzonMailDesktop.Localization;

/// <summary>
/// 桌面端可本地化文本的资源键
/// </summary>
public enum DesktopTextKey
{
    ApplicationTitle,
    StartupTitle,
    StartupSubtitle,
    StartupCheckingEnvironment,
    StartupMissingPrerequisites,
    StartupStartingBackend,
    StartupInstallFailed,
    StartupCheckFailed,
    StartupDownloadWebView,
    StartupInstallWebView,
    StartupDownloadingPrerequisite,
    StartupInstallingPrerequisite,
    StartupPrerequisitesInstalled,
    ButtonRetry,
    ButtonOpenDownloadPage,
    ButtonInstallAndContinue,
    ButtonExit,
    DialogUpdaterTitle,
    DialogUpdaterInstallFailed,
    DialogSingleInstanceTitle,
    DialogSingleInstanceMessage,
    DialogStartupFailedTitle,
    WebViewInitializationFailed,
    HostObjectInitializationFailed,
    BackendExecutableNotFound,
    BackendWorkingDirectoryNotFound,
    BackendProcessStartFailed,
    BackendProcessExited,
    BackendStartupTimedOut,
    RuntimeConfigNotFound,
    PrerequisiteVersionMissing,
    PrerequisiteInstallerNotFound,
    PrerequisiteInstallerValidationFailed,
    PrerequisiteInstallerSignatureInvalid,
    PrerequisiteInstallerPublisherInvalid,
    PrerequisiteInstallerStartFailed,
    PrerequisiteInstallerExitCode,
    PrerequisiteAdministratorCanceled,
    TrayOpen,
    TrayExit,
    TrayExitConfirmationMessage,
    TrayExitConfirmationTitle,
    TrayIconResourceMissing,
    BackendExecutablePathInvalid,
    BackendWebUrlInvalid,
    BackendReadinessUrlInvalid,
    BackendStartupTimeoutInvalid,
    PrerequisiteMetadataUrlInvalid,
    PrerequisiteWebViewUrlInvalid,
    UpdaterInvalidPath
}
