/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AsyncTooltip: typeof import('./src/components/asyncTooltip/AsyncTooltip.vue')['default']
    ButtonsGroup: typeof import('./src/components/buttonsGroup/ButtonsGroup.vue')['default']
    CancelBtn: typeof import('./src/components/quasarWrapper/buttons/CancelBtn.vue')['default']
    ClickableText: typeof import('./src/components/clickableText/ClickableText.vue')['default']
    CollapseLeft: typeof import('./src/components/collapseLeft/CollapseLeft.vue')['default']
    CommonBtn: typeof import('./src/components/quasarWrapper/buttons/CommonBtn.vue')['default']
    ContextMenu: typeof import('./src/components/contextMenu/ContextMenu.vue')['default']
    CreateBtn: typeof import('./src/components/quasarWrapper/buttons/CreateBtn.vue')['default']
    DeleteBtn: typeof import('./src/components/quasarWrapper/buttons/DeleteBtn.vue')['default']
    EllipsisContent: typeof import('./src/components/ellipsisContent/EllipsisContent.vue')['default']
    ExportBtn: typeof import('./src/components/quasarWrapper/buttons/ExportBtn.vue')['default']
    FilesUploaderPopup: typeof import('./src/components/uploader/FilesUploaderPopup.vue')['default']
    HoverableTip: typeof import('./src/components/hoverableTip/HoverableTip.vue')['default']
    HtmlDialog: typeof import('./src/components/popupDialog/HtmlDialog.vue')['default']
    ImageCropper: typeof import('./src/components/imageCropper/ImageCropper.vue')['default']
    ImportBtn: typeof import('./src/components/quasarWrapper/buttons/ImportBtn.vue')['default']
    LinearProgress: typeof import('./src/components/Progress/LinearProgress.vue')['default']
    LowCodeForm: typeof import('./src/components/popupDialog/LowCodeForm.vue')['default']
    ObjectUploader: typeof import('./src/components/uploader/ObjectUploader.vue')['default']
    OkBtn: typeof import('./src/components/quasarWrapper/buttons/OkBtn.vue')['default']
    PasswordInput: typeof import('./src/components/passwordInput/PasswordInput.vue')['default']
    PopupDialogExample: typeof import('./src/components/quasarWrapper/PopupDialogExample.vue')['default']
    QTableWrapper: typeof import('./src/components/quasarWrapper/QTableWrapper.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./src/components/searchInput/SearchInput.vue')['default']
    StatusChip: typeof import('./src/components/statusChip/StatusChip.vue')['default']
    TableIndex: typeof import('./src/components/tableComponents/TableIndex.vue')['default']
    UserAvatar: typeof import('./src/components/userAvatar/UserAvatar.vue')['default']
  }
}
