// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UZonMail.DB.MySql;

#nullable disable

namespace UZonMail.DB.Migrations.Mysql
{
    [DbContext(typeof(MySqlContext))]
    [Migration("20250506231014_removeOrgSetting")]
    partial class removeOrgSetting
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PermissionCodeRole", b =>
                {
                    b.Property<long>("PermissionCodesId")
                        .HasColumnType("bigint");

                    b.Property<long>("RolesId")
                        .HasColumnType("bigint");

                    b.HasKey("PermissionCodesId", "RolesId");

                    b.HasIndex("RolesId");

                    b.ToTable("PermissionCodeRole");
                });

            modelBuilder.Entity("RoleUserRoles", b =>
                {
                    b.Property<long>("RolesId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserRolesId")
                        .HasColumnType("bigint");

                    b.HasKey("RolesId", "UserRolesId");

                    b.HasIndex("UserRolesId");

                    b.ToTable("RoleUserRoles");
                });

            modelBuilder.Entity("UZonMail.DB.SQL.Base.IdAndName", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("_id");

                    b.HasKey("Id");

                    b.ToTable("IdAndName");
                });

            modelBuilder.Entity("UZonMail.DB.SQL.Core.EmailSending.EmailAddress", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("_id");

                    b.HasKey("Id");

                    b.ToTable("EmailAddress");
                });

            modelBuilder.Entity("UZonMail.DB.SQL.Core.EmailSending.SendingGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BccBoxes")
                        .HasColumnType("longtext");

                    b.Property<string>("Body")
                        .HasColumnType("longtext");

                    b.Property<string>("CcBoxes")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Data")
                        .HasColumnType("longtext");

                    b.Property<string>("InboxGroups")
                        .HasColumnType("longtext");

                    b.Property<string>("Inboxes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("InboxesCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDistributed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastMessage")
                        .HasColumnType("longtext");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("_id");

                    b.Property<string>("OutboxGroups")
                        .HasColumnType("longtext");

                    b.Property<int>("OutboxesCount")
                        .HasColumnType("int");

                    b.Property<string>("ProxyIds")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ScheduleDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("SendEndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("SendStartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SendingType")
                        .HasColumnType("int");

                    b.Property<int>("SentCount")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Subjects")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SuccessCount")
                        .HasColumnType("int");

                    b.Property<int>("TotalCount")
                        .HasColumnType("int");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("SendingGroups");
                });

            modelBuilder.Entity("UZonMail.DB.SQL.Core.EmailSending.SendingItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BCC")
                        .HasColumnType("longtext");

                    b.Property<string>("CC")
                        .HasColumnType("longtext");

                    b.Property<string>("Content")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Data")
                        .HasColumnType("longtext");

                    b.Property<long>("EmailTemplateId")
                        .HasColumnType("bigint");

                    b.Property<bool>("EnableEmailTracker")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FromEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("Inboxes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsSendingBatch")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("_id");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<long>("OutBoxId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProxyId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ReadDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ReceiptId")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("SendDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SendResult")
                        .HasColumnType("longtext");

                    b.Property<long>("SendingGroupId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .HasColumnType("longtext");

                    b.Property<string>("ToEmails")
                        .HasColumnType("longtext");

                    b.Property<int>("TriedCount")
                        .HasColumnType("int");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SendingGroupId");

                    b.ToTable("SendingItems");
                });

            modelBuilder.Entity("UZonMail.DB.SQL.Core.EmailSending.SendingItemInbox", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FromEmail")
                        .HasColumnType("longtext");

                    b.Property<long>("InboxId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("_id");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime>("SendDate")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("SendingItemId")
                        .HasColumnType("bigint");

                    b.Property<string>("ToEmail")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("InboxId");

                    b.HasIndex("SendingItemId");

                    b.ToTable("SendingItemInboxes");
                });

            modelBuilder.Entity("UZonMail.DB.SQL.Core.Emails.EmailGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Icon")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("_id");

                    b.Property<long>("Order")
                        .HasColumnType("bigint");

                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("EmailGroups");
                });

            modelBuilder.Entity("UZonMail.DB.SQL.Core.Emails.Inbox", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Domain")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<long>("EmailGroupId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastBeDeliveredDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("LastSuccessDeliveryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LinkCount")
                        .HasColumnType("int");

                    b.Property<long>("MinInboxCooldownHours")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("_id");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Remark")
                        .HasColumnType("longtext");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("ValidFailReason")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("EmailGroupId");

                    b.HasIndex("Email", "UserId")
                        .IsUnique();

                    b.ToTable("Inboxes");
                });

            modelBuilder.Entity("UZonMail.DB.SQL.Core.Emails.Outbox", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Domain")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<long>("EmailGroupId")
                        .HasColumnType("bigint");

                    b.Property<bool>("EnableSSL")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsValid")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("LinkCount")
                        .HasColumnType("int");

                    b.Property<int>("MaxSendCountPerDay")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("_id");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("ProxyId")
                        .HasColumnType("bigint");

                    b.Property<string>("Remark")
                        .HasColumnType("longtext");

                    b.Property<string>("ReplyToEmails")
                        .HasColumnType("longtext");

                    b.Property<long?>("SendingGroupId")
                        .HasColumnType("bigint");

                    b.Property<int>("SentTotalToday")
                        .HasColumnType("int");

                    b.Property<string>("SmtpHost")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SmtpPort")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserName")
                        .HasColumnType("longtext");

                    b.Property<string>("ValidFailReason")
                        .HasColumnType("longtext");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SendingGroupId");

                    b.HasIndex("Email", "UserId")
                        .IsUnique();

                    b.ToTable("Outboxes");
                });

            modelBuilder.Entity("UZonMail.DB.SQL.Core.Emails.SmtpInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("EnableSSL")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("_id");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<int>("SecurityProtocol")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SmtpInfos");
                });

            modelBuilder.Entity("UZonMail.DB.SQL.Core.Files.FileBucket", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BucketName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("_id");

                    b.Property<string>("RootDir")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("FileBuckets");
                });

            modelBuilder.Entity("UZonMail.DB.SQL.Core.Files.FileObject", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("FileBucketId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastModifyDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LinkCount")
                        .HasColumnType("int");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("_id");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FileBucketId");

                    b.ToTable("FileObjects");
                });

            modelBuilder.Entity("UZonMail.DB.SQL.Core.Files.FileReader", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpireDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("FileObjectId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("FirstDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MaxVisitCount")
                        .HasColumnType("int");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<int>("VisitedCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FileObjectId");

                    b.ToTable("FileReaders");
                });

            modelBuilder.Entity("UZonMail.DB.SQL.Core.Files.FileUsage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("FileObjectId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("_id");

                    b.Property<long>("OwnerUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SendingGroupId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SendingItemId")
                        .HasColumnType("bigint");

                    b.Property<string>("UniqueName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("FileObjectId");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("SendingGroupId");

                    b.HasIndex("SendingItemId");

                    b.ToTable("FileUsages");
                });

            modelBuilder.Entity("UZonMail.DB.SQL.Core.Organization.Department", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<long?>("EmailTemplateId")
                        .HasColumnType("bigint");

                    b.Property<string>("FullPath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("_id");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmailTemplateId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("UZonMail.DB.SQL.Core.Organization.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Avatar")
                        .HasColumnType("longtext");

                    b.Property<string>("ConnectionId")
                        .HasColumnType("longtext");

                    b.Property<long>("CreateBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("DepartmentId")
                        .HasColumnType("bigint");

                    b.Property<long?>("EmailTemplateId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsSuperAdmin")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsSystsemUser")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("_id");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .HasColumnType("longtext");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmailTemplateId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UZonMail.DB.SQL.Core.Permission.PermissionCode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsNegative")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("_id");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("PermissionCodes");
                });

            modelBuilder.Entity("UZonMail.DB.SQL.Core.Permission.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Icon")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("_id");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<int>("PermissionCodesCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("UZonMail.DB.SQL.Core.Permission.UserRoles", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("_id");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserRole");
                });

            modelBuilder.Entity("UZonMail.DB.SQL.Core.Settings.AppSetting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("BoolValue")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IntValue")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Json")
                        .HasColumnType("longtext");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("LongValue")
                        .HasColumnType("bigint");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("_id");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<string>("StringValue")
                        .HasColumnType("longtext");

                    b.Property<int?>("Type")
                        .HasColumnType("int");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("UZonMail.DB.SQL.Core.Settings.Proxy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsShared")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MatchRegex")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("_id");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Proxies");
                });

            modelBuilder.Entity("UZonMail.DB.SQL.Core.Templates.EmailTemplate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("_id");

                    b.Property<long?>("SendingGroupId")
                        .HasColumnType("bigint");

                    b.Property<string>("Thumbnail")
                        .HasColumnType("longtext");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SendingGroupId");

                    b.ToTable("EmailTemplates");
                });

            modelBuilder.Entity("PermissionCodeRole", b =>
                {
                    b.HasOne("UZonMail.DB.SQL.Core.Permission.PermissionCode", null)
                        .WithMany()
                        .HasForeignKey("PermissionCodesId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("UZonMail.DB.SQL.Core.Permission.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("RoleUserRoles", b =>
                {
                    b.HasOne("UZonMail.DB.SQL.Core.Permission.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("UZonMail.DB.SQL.Core.Permission.UserRoles", null)
                        .WithMany()
                        .HasForeignKey("UserRolesId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("UZonMail.DB.SQL.Core.EmailSending.SendingItem", b =>
                {
                    b.HasOne("UZonMail.DB.SQL.Core.EmailSending.SendingGroup", "SendingGroup")
                        .WithMany()
                        .HasForeignKey("SendingGroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("SendingGroup");
                });

            modelBuilder.Entity("UZonMail.DB.SQL.Core.EmailSending.SendingItemInbox", b =>
                {
                    b.HasOne("UZonMail.DB.SQL.Core.Emails.Inbox", "Inbox")
                        .WithMany()
                        .HasForeignKey("InboxId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("UZonMail.DB.SQL.Core.EmailSending.SendingItem", "SendingItem")
                        .WithMany()
                        .HasForeignKey("SendingItemId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Inbox");

                    b.Navigation("SendingItem");
                });

            modelBuilder.Entity("UZonMail.DB.SQL.Core.Emails.EmailGroup", b =>
                {
                    b.HasOne("UZonMail.DB.SQL.Core.Organization.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UZonMail.DB.SQL.Core.Emails.Inbox", b =>
                {
                    b.HasOne("UZonMail.DB.SQL.Core.Emails.EmailGroup", null)
                        .WithMany("Inboxes")
                        .HasForeignKey("EmailGroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("UZonMail.DB.SQL.Core.Emails.Outbox", b =>
                {
                    b.HasOne("UZonMail.DB.SQL.Core.EmailSending.SendingGroup", null)
                        .WithMany("Outboxes")
                        .HasForeignKey("SendingGroupId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("UZonMail.DB.SQL.Core.Files.FileObject", b =>
                {
                    b.HasOne("UZonMail.DB.SQL.Core.Files.FileBucket", "FileBucket")
                        .WithMany()
                        .HasForeignKey("FileBucketId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("FileBucket");
                });

            modelBuilder.Entity("UZonMail.DB.SQL.Core.Files.FileReader", b =>
                {
                    b.HasOne("UZonMail.DB.SQL.Core.Files.FileObject", "FileObject")
                        .WithMany()
                        .HasForeignKey("FileObjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("FileObject");
                });

            modelBuilder.Entity("UZonMail.DB.SQL.Core.Files.FileUsage", b =>
                {
                    b.HasOne("UZonMail.DB.SQL.Core.Files.FileObject", "FileObject")
                        .WithMany()
                        .HasForeignKey("FileObjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("UZonMail.DB.SQL.Core.Organization.User", "OwnerUser")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("UZonMail.DB.SQL.Core.EmailSending.SendingGroup", null)
                        .WithMany("Attachments")
                        .HasForeignKey("SendingGroupId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("UZonMail.DB.SQL.Core.EmailSending.SendingItem", null)
                        .WithMany("Attachments")
                        .HasForeignKey("SendingItemId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("FileObject");

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("UZonMail.DB.SQL.Core.Organization.Department", b =>
                {
                    b.HasOne("UZonMail.DB.SQL.Core.Templates.EmailTemplate", null)
                        .WithMany("ShareToOrganizations")
                        .HasForeignKey("EmailTemplateId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("UZonMail.DB.SQL.Core.Organization.User", b =>
                {
                    b.HasOne("UZonMail.DB.SQL.Core.Templates.EmailTemplate", null)
                        .WithMany("ShareToUsers")
                        .HasForeignKey("EmailTemplateId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("UZonMail.DB.SQL.Core.Permission.UserRoles", b =>
                {
                    b.HasOne("UZonMail.DB.SQL.Core.Organization.User", "User")
                        .WithOne("UserRoles")
                        .HasForeignKey("UZonMail.DB.SQL.Core.Permission.UserRoles", "UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UZonMail.DB.SQL.Core.Templates.EmailTemplate", b =>
                {
                    b.HasOne("UZonMail.DB.SQL.Core.EmailSending.SendingGroup", null)
                        .WithMany("Templates")
                        .HasForeignKey("SendingGroupId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("UZonMail.DB.SQL.Core.EmailSending.SendingGroup", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Outboxes");

                    b.Navigation("Templates");
                });

            modelBuilder.Entity("UZonMail.DB.SQL.Core.EmailSending.SendingItem", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("UZonMail.DB.SQL.Core.Emails.EmailGroup", b =>
                {
                    b.Navigation("Inboxes");
                });

            modelBuilder.Entity("UZonMail.DB.SQL.Core.Organization.User", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("UZonMail.DB.SQL.Core.Templates.EmailTemplate", b =>
                {
                    b.Navigation("ShareToOrganizations");

                    b.Navigation("ShareToUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
