# 
# 说明
# 该文件是 uzon-mail 的 docker-compose 配置文件，使用时，在当前目录执行 docker-compose up -d 命令即可启动程序
#

services:
  # PostgreSQL 服务
  uzon-postgres:
    container_name: uzon-postgres
    image: postgres:18-alpine
    # [可选]对外暴露端口，方便外部管理
    # 本地端口:容器端口
    # 若本机 5432 已使用，可更换成其它端口，例如 25432:5432
    # ports:
    #   - 5432:5432
    environment:
      POSTGRES_DB: uzon-mail # 数据库名
      POSTGRES_USER: uzon-mail # 数据库用户名
      POSTGRES_PASSWORD: uzon-mail # 数据库密码
    volumes:
      - ./data/postgresql/data:/var/lib/postgresql/data # 数据库数据挂载，防止容器重构后数据丢失
    restart: always
    # 连接到 uzonmail 主程序网络
    networks:
      - uzon_postgres_network

  # redis 缓存, 若要启用 redis 服务，请取消下面的注释
  uzon-redis:
    container_name: uzon-redis
    image: redis:latest
    # [可选]对外暴露端口，方便外部管理
    # 本地端口:容器端口
    # 若本机 6379 已使用，可更换成其它端口，例如 26379:3306
    # ports:
    #   - 6379:6379
    volumes:
      - ./data/redis/data:/data # 数据库数据挂载，防止容器重构后数据丢失
    restart: always
    networks:
      - uzon_redis_network

  # 程序主体
  uzon-mail:
    container_name: uzon-mail
    image: gmxgalens/uzon-mail:latest
    ports:
      - 22345:22345
    volumes:      
      - ./data/data:/app/data # 数据存储
    # - ./data/appsettings.Production.json:/app/appsettings.Production.json:ro # 生产环境配置
    # - ./data/app.config.json:/app/wwwroot/app.config.json # 前端配置, 可选
    networks:
      - uzonmail_network
      - uzon_postgres_network
      - uzon_redis_network
    command: [ "dotnet", "UZonMailService.dll" ]
    depends_on:
      uzon-postgres:
        condition: service_started
      uzon-redis:
        condition: service_started

networks:
  uzon_postgres_network:
  uzon_redis_network:
  uzonmail_network:
