<Project Sdk="MSTest.Sdk/4.0.1">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<RootNamespace>UzonMailDotNET.Test</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\api\Plugins\UZonMailCorePlugin\UZonMailCorePlugin.csproj" />
    <ProjectReference Include="..\..\src\api\Plugins\UzonMailProPlugin\UZonMailProPlugin.csproj" />
    <ProjectReference Include="..\..\src\api\UzonMailDB\UzonMailDB.csproj" />
    <ProjectReference Include="..\..\src\api\UzonMailService\UzonMailService.csproj" />
    <ProjectReference Include="..\..\src\api\UzonMailUtils\UzonMailUtils.csproj" />
  </ItemGroup>

	<ItemGroup>
	  <Folder Include="UzonMail.Desktop\" />
	  <Folder Include="UzonMail.Utils\" />
	  <Folder Include="UzonMail.DB\" />
	</ItemGroup>

</Project>
